/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.16-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.SalesEmployee;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-10-12T13:17:48.921+02:00")

@Api(value = "salesEmployees", description = "the salesEmployees API")
@RequestMapping(value = "")
public interface SalesEmployeesApi {

    @ApiOperation(value = "all", nickname = "allUsingGET", notes = "", response = SalesEmployee.class, responseContainer = "List", tags={ "sales-employee-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SalesEmployee.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/salesEmployees",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<SalesEmployee>> allUsingGET();

}
