/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Appointment;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppointmentControllerApi
 */
@Ignore
public class AppointmentControllerApiTest {

    private final AppointmentControllerApi api = new AppointmentControllerApi();

    
    /**
     * getBySalesId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBySalesIdUsingGETTest() throws ApiException {
        Long id = null;
        List<Appointment> response = api.getBySalesIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * getProposals
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProposalsUsingGETTest() throws ApiException {
        String address = null;
        List<Long> salesIds = null;
        List<Appointment> response = api.getProposalsUsingGET(address, salesIds);

        // TODO: test validations
    }
    
    /**
     * newAppointment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newAppointmentUsingPOSTTest() throws ApiException {
        Appointment appointment = null;
        Appointment response = api.newAppointmentUsingPOST(appointment);

        // TODO: test validations
    }
    
}
